### ISSUE TITLE
I can't compile with UFBT

### ISSUE THREAD

**Issue by ljorge705** [acegoal07/FlipperZero_NFC_Playlist#4]
give me this error 
![11111](https://github.com/acegoal07/FlipperZero_NFC_Playlist/assets/43147213/a12418b6-39b3-4d9e-b5ce-88068edb5a14)

what firmware do you use?
can you build it and upload the fap on releases?

**Comment by acegoal07** [comment]
I use xtreme firmware and have a functioning build what firmware are you trying to build with?

Could I also ask what branch you are trying to build?

**Comment by ljorge705** [comment]
na bro give me error, but its my fault, can you share the fap

sorry for my bad english

**Comment by acegoal07** [comment]
On release I'll publish some faps which shouldn't be too far off from first release

But till then I would try using fbt to compile it instead of ufbt
